### ISSUE TITLE
Ipa please

### ISSUE THREAD

**Issue by travis414** [CoryKornowicz/Alticha-voucher_swap-Razmashat-RootKit-voucher_swap#4]
Appreciate the hard work. 🔥Can you compile an ipa please? Thx

**Comment by CoryKornowicz** [comment]
Huge credit to u/LiamMcKee- compiled ipa https://drive.google.com/open?id=12qBARyeXR7dQbIFqSsJN06SZyh-3iJag

it is also linked on the reddit page- https://www.reddit.com/r/jailbreak/comments/amccvj/discussion_ive_merged_altichavoucher_swap_with/

**Comment by travis414** [comment]
Thx🌊🏄‍♂️
